// <auto-generated />
using System;
using DWM.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DWM.Persistence.Migrations
{
    [DbContext(typeof(DWMBestiarySqlServerDbContext))]
    [Migration("20241224003221_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DWM.Models.BreedingPair", b =>
                {
                    b.Property<int>("BreedingPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreedingPairId"), 1L, 1);

                    b.Property<int>("OffspringMonsterId")
                        .HasColumnType("int");

                    b.Property<int?>("OffspringPlusRequirement")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerFamilyId")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerMonsterId")
                        .HasColumnType("int");

                    b.Property<int?>("PedigreeFamilyId")
                        .HasColumnType("int");

                    b.Property<int?>("PedigreeMonsterId")
                        .HasColumnType("int");

                    b.Property<int?>("PedigreePlusRequirement")
                        .HasColumnType("int");

                    b.HasKey("BreedingPairId");

                    b.HasIndex("OffspringMonsterId");

                    b.HasIndex("PartnerMonsterId");

                    b.HasIndex("PedigreeMonsterId");

                    b.ToTable("BreedingPairs");
                });

            modelBuilder.Entity("DWM.Models.GrowthCategory", b =>
                {
                    b.Property<int>("GrowthCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("GrowthStatistics")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("GrowthCategoryId");

                    b.ToTable("GrowthCategories");
                });

            modelBuilder.Entity("DWM.Models.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterId"), 1L, 1);

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<int>("GenderProbabilityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFlying")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMetal")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<string>("MonsterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WildnessLevel")
                        .HasColumnType("int");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("DWM.Models.MonsterGrowth", b =>
                {
                    b.Property<int>("MonsterGrowthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterGrowthId"), 1L, 1);

                    b.Property<int>("GrowthCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.HasKey("MonsterGrowthId");

                    b.HasIndex("GrowthCategoryId");

                    b.HasIndex("MonsterId");

                    b.ToTable("MonsterGrowths");
                });

            modelBuilder.Entity("DWM.Models.MonsterLocation", b =>
                {
                    b.Property<int>("MonsterLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonsterLocationId"), 1L, 1);

                    b.Property<int>("MaxLevelEncountered")
                        .HasColumnType("int");

                    b.Property<int>("MinLevelEncountered")
                        .HasColumnType("int");

                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<string>("TravelersGateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MonsterLocationId");

                    b.HasIndex("MonsterId");

                    b.ToTable("MonsterLocations");
                });

            modelBuilder.Entity("DWM.Models.NaturalSkill", b =>
                {
                    b.Property<int>("NaturalSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NaturalSkillId"), 1L, 1);

                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("NaturalSkillId");

                    b.HasIndex("MonsterId");

                    b.HasIndex("SkillId");

                    b.ToTable("NaturalSkills");
                });

            modelBuilder.Entity("DWM.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"), 1L, 1);

                    b.Property<int>("SkillClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("SkillDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DWM.Models.SkillComboRequirement", b =>
                {
                    b.Property<int>("SkillComboRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillComboRequirementId"), 1L, 1);

                    b.Property<int>("RequiredSkillId")
                        .HasColumnType("int");

                    b.Property<int>("TargetSkillId")
                        .HasColumnType("int");

                    b.HasKey("SkillComboRequirementId");

                    b.HasIndex("RequiredSkillId");

                    b.HasIndex("TargetSkillId");

                    b.ToTable("SkillComboRequirements");
                });

            modelBuilder.Entity("DWM.Models.SkillResistance", b =>
                {
                    b.Property<int>("SkillResistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillResistanceId"), 1L, 1);

                    b.Property<int>("MonsterId")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceLevel")
                        .HasColumnType("int");

                    b.Property<int>("SkillClassificationId")
                        .HasColumnType("int");

                    b.HasKey("SkillResistanceId");

                    b.HasIndex("MonsterId");

                    b.ToTable("SkillResistances");
                });

            modelBuilder.Entity("DWM.Models.SkillStatRequirement", b =>
                {
                    b.Property<int>("SkillStatRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillStatRequirementId"), 1L, 1);

                    b.Property<int>("RequiredValue")
                        .HasColumnType("int");

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("TargetSkillId")
                        .HasColumnType("int");

                    b.HasKey("SkillStatRequirementId");

                    b.HasIndex("TargetSkillId");

                    b.ToTable("SkillStatRequirements");
                });

            modelBuilder.Entity("DWM.Models.SkillUpgrade", b =>
                {
                    b.Property<int>("SkillUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillUpgradeId"), 1L, 1);

                    b.Property<int>("BaseSkillId")
                        .HasColumnType("int");

                    b.Property<int>("UpgradedSkillId")
                        .HasColumnType("int");

                    b.HasKey("SkillUpgradeId");

                    b.HasIndex("BaseSkillId");

                    b.HasIndex("UpgradedSkillId");

                    b.ToTable("SkillUpgrades");
                });

            modelBuilder.Entity("DWM.Models.BreedingPair", b =>
                {
                    b.HasOne("DWM.Models.Monster", "OffspringMonster")
                        .WithMany()
                        .HasForeignKey("OffspringMonsterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DWM.Models.Monster", "PartnerMonster")
                        .WithMany()
                        .HasForeignKey("PartnerMonsterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DWM.Models.Monster", "PedigreeMonster")
                        .WithMany()
                        .HasForeignKey("PedigreeMonsterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OffspringMonster");

                    b.Navigation("PartnerMonster");

                    b.Navigation("PedigreeMonster");
                });

            modelBuilder.Entity("DWM.Models.MonsterGrowth", b =>
                {
                    b.HasOne("DWM.Models.GrowthCategory", "GrowthCategory")
                        .WithMany()
                        .HasForeignKey("GrowthCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DWM.Models.Monster", "Monster")
                        .WithMany("StatGrowth")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GrowthCategory");

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("DWM.Models.MonsterLocation", b =>
                {
                    b.HasOne("DWM.Models.Monster", "Monster")
                        .WithMany("MonsterLocations")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("DWM.Models.NaturalSkill", b =>
                {
                    b.HasOne("DWM.Models.Monster", null)
                        .WithMany("NaturalSkills")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DWM.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DWM.Models.SkillComboRequirement", b =>
                {
                    b.HasOne("DWM.Models.Skill", "RequiredSkill")
                        .WithMany()
                        .HasForeignKey("RequiredSkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DWM.Models.Skill", "TargetSkill")
                        .WithMany("ComboRequirements")
                        .HasForeignKey("TargetSkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RequiredSkill");

                    b.Navigation("TargetSkill");
                });

            modelBuilder.Entity("DWM.Models.SkillResistance", b =>
                {
                    b.HasOne("DWM.Models.Monster", null)
                        .WithMany("SkillResistances")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DWM.Models.SkillStatRequirement", b =>
                {
                    b.HasOne("DWM.Models.Skill", "TargetSkill")
                        .WithMany("StatRequirements")
                        .HasForeignKey("TargetSkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TargetSkill");
                });

            modelBuilder.Entity("DWM.Models.SkillUpgrade", b =>
                {
                    b.HasOne("DWM.Models.Skill", "BaseSkill")
                        .WithMany("AvailableUpgrades")
                        .HasForeignKey("BaseSkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DWM.Models.Skill", "UpgradedSkill")
                        .WithMany()
                        .HasForeignKey("UpgradedSkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseSkill");

                    b.Navigation("UpgradedSkill");
                });

            modelBuilder.Entity("DWM.Models.Monster", b =>
                {
                    b.Navigation("MonsterLocations");

                    b.Navigation("NaturalSkills");

                    b.Navigation("SkillResistances");

                    b.Navigation("StatGrowth");
                });

            modelBuilder.Entity("DWM.Models.Skill", b =>
                {
                    b.Navigation("AvailableUpgrades");

                    b.Navigation("ComboRequirements");

                    b.Navigation("StatRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
